package com.zeta.store

internal data class PeruProvinceUi(
    val name: String,
    val districts: List<String>,
)

internal data class PeruRegionUi(
    val name: String,
    val provinces: List<PeruProvinceUi>,
)

internal val peruRegions = listOf(
    PeruRegionUi(
        name = "Amazonas",
        provinces = listOf(
            PeruProvinceUi("Chachapoyas", listOf("Chachapoyas", "Asuncion", "Balsas", "Cheto", "Chiliquin", "Chuquibamba", "Granada", "Huancas", "La Jalca", "Leimebamba", "Levanto", "Magdalena", "Mariscal Castilla", "Molinopampa", "Montevideo", "Olleros", "Quinjalca", "San Francisco de Daguas", "San Isidro de Maino", "Soloco", "Sonche")),
            PeruProvinceUi("Bagua", listOf("Bagua", "Aramango", "Copallin", "El Parco", "Imaza", "La Peca")),
            PeruProvinceUi("Bongara", listOf("Jumbilla", "Chisquilla", "Churuja", "Corosha", "Cuispes", "Florida", "Jazan", "Recta", "San Carlos", "Shipasbamba", "Valera", "Yambrasbamba")),
            PeruProvinceUi("Condorcanqui", listOf("Nieva", "El Cenepa", "Rio Santiago")),
            PeruProvinceUi("Luya", listOf("Lamud", "Camporredondo", "Cocabamba", "Colcamar", "Conila", "Inguilpata", "Longuita", "Lonya Chico", "Luya", "Luya Viejo", "Maria", "Ocalli", "Ocumal", "Pisuquia", "Providencia", "San Cristobal", "San Francisco del Yeso", "San Jeronimo", "San Juan de Lopecancha", "Santa Catalina", "Santo Tomas", "Tingo", "Trita")),
            PeruProvinceUi("Rodriguez de Mendoza", listOf("San Nicolas", "Chirimoto", "Cochamal", "Huambo", "Limabamba", "Longar", "Mariscal Benavides", "Milpuc", "Omia", "Santa Rosa", "Totora", "Vista Alegre")),
            PeruProvinceUi("Utcubamba", listOf("Bagua Grande", "Cajaruro", "Cumba", "El Milagro", "Jamalca", "Lonya Grande", "Yamon")),
        ),
    ),
    PeruRegionUi(
        name = "Ancash",
        provinces = listOf(
            PeruProvinceUi("Huaraz", listOf("Huaraz", "Cochabamba", "Colcabamba", "Huanchay", "Independencia", "Jangas", "La Libertad", "Olleros", "Pampas", "Pariacoto", "Pira", "Tarica")),
            PeruProvinceUi("Aija", listOf("Aija", "Coris", "Huacllan", "La Merced", "Succha")),
            PeruProvinceUi("Antonio Raymondi", listOf("Llamellin", "Aczo", "Chaccho", "Chingas", "Mirgas", "San Juan de Rontoy")),
            PeruProvinceUi("Asuncion", listOf("Chacas", "Acochaca")),
            PeruProvinceUi("Bolognesi", listOf("Chiquian", "Abelardo Pardo Lezameta", "Antonio Raymondi", "Aquia", "Cajacay", "Canis", "Colquioc", "Huallanca", "Huasta", "Huayllacayan", "La Primavera", "Mangas", "Pacllon", "San Miguel de Corpanqui", "Ticllos")),
            PeruProvinceUi("Carhuaz", listOf("Carhuaz", "Acopampa", "Amashca", "Anta", "Ataquero", "Marcara", "Pariahuanca", "San Miguel de Aco", "Shilla", "Tinco", "Yungar")),
            PeruProvinceUi("Carlos Fermin Fitzca", listOf("San Luis", "San Nicolas", "Yauya")),
            PeruProvinceUi("Casma", listOf("Casma", "Buena Vista Alta", "Comandante Noel", "Yautan")),
            PeruProvinceUi("Corongo", listOf("Corongo", "Aco", "Bambas", "Cusca", "La Pampa", "Yanac", "Yupan")),
            PeruProvinceUi("Huari", listOf("Huari", "Anra", "Cajay", "Chavin de Huantar", "Huacachi", "Huacchis", "Huachis", "Huantar", "Masin", "Paucas", "Ponto", "Rahuapampa", "Rapayan", "San Marcos", "San Pedro de Chana", "Uco")),
            PeruProvinceUi("Huarmey", listOf("Huarmey", "Cochapeti", "Culebras", "Huayan", "Malvas")),
            PeruProvinceUi("Huaylas", listOf("Caraz", "Huallanca", "Huata", "Huaylas", "Mato", "Pamparomas", "Pueblo Libre", "Santa Cruz", "Santo Toribio", "Yuracmarca")),
            PeruProvinceUi("Mariscal Luzuriaga", listOf("Piscobamba", "Casca", "Eleazar Guzman Barron", "Fidel Olivas Escudero", "Llama", "Llumpa", "Lucma", "Musga")),
            PeruProvinceUi("Ocros", listOf("Ocros", "Acas", "Cajamarquilla", "Carhuapampa", "Cochas", "Congas", "Llipa", "San Cristobal de Rajan", "San Pedro", "Santiago de Chilcas")),
            PeruProvinceUi("Pallasca", listOf("Cabana", "Bolognesi", "Conchucos", "Huacaschuque", "Huandoval", "Lacabamba", "Llapo", "Pallasca", "Pampas", "Santa Rosa", "Tauca")),
            PeruProvinceUi("Pomabamba", listOf("Pomabamba", "Huayllan", "Parobamba", "Quinuabamba")),
            PeruProvinceUi("Recuay", listOf("Recuay", "Catac", "Cotaparaco", "Huayllapampa", "Llacllin", "Marca", "Pampas Chico", "Pararin", "Tapacocha", "Ticapampa")),
            PeruProvinceUi("Santa", listOf("Chimbote", "Caceres del Peru", "Coishco", "Macate", "Moro", "Nepena", "Samanco", "Santa", "Nuevo Chimbote")),
            PeruProvinceUi("Sihuas", listOf("Sihuas", "Acobamba", "Alfonso Ugarte", "Cashapampa", "Chingalpo", "Huayllabamba", "Quiches", "Ragash", "San Juan", "Sicsibamba")),
            PeruProvinceUi("Yungay", listOf("Yungay", "Cascapara", "Mancos", "Matacoto", "Quillo", "Ranrahirca", "Shupluy", "Yanama")),
        ),
    ),
    PeruRegionUi(
        name = "Apurimac",
        provinces = listOf(
            PeruProvinceUi("Abancay", listOf("Abancay", "Chacoche", "Circa", "Curahuasi", "Huanipaca", "Lambrama", "Pichirhua", "San Pedro de Cachora", "Tamburco")),
            PeruProvinceUi("Andahuaylas", listOf("Andahuaylas", "Andarapa", "Chiara", "Huancarama", "Huancaray", "Huayana", "Kishuara", "Pacobamba", "Pacucha", "Pampachiri", "Pomacocha", "San Antonio de Cachi", "San Jeronimo", "San Miguel de Chaccrampa", "Santa Maria de Chicmo", "Talavera", "Tumay Huaraca", "Turpo", "Kaquiabamba", "Jose Maria Arguedas")),
            PeruProvinceUi("Antabamba", listOf("Antabamba", "El Oro", "Huaquirca", "Juan Espinoza Medrano", "Oropesa", "Pachaconas", "Sabaino")),
            PeruProvinceUi("Aymaraes", listOf("Chalhuanca", "Capaya", "Caraybamba", "Chapimarca", "Colcabamba", "Cotaruse", "Huayllo", "Justo Apu Sahuaraura", "Lucre", "Pocohuanca", "San Juan de Chacna", "Sanayca", "Soraya", "Tapairihua", "Tintay", "Toraya", "Yanaca")),
            PeruProvinceUi("Cotabambas", listOf("Tambobamba", "Cotabambas", "Coyllurqui", "Haquira", "Mara", "Challhuahuacho")),
            PeruProvinceUi("Chincheros", listOf("Chincheros", "Anco_Huallo", "Cocharcas", "Huaccana", "Ocobamba", "Ongoy", "Uranmarca", "Ranracancha", "Rocchacc", "El Porvenir", "Los Chankas")),
            PeruProvinceUi("Grau", listOf("Chuquibambilla", "Curpahuasi", "Gamarra", "Huayllati", "Mamara", "Micaela Bastidas", "Pataypampa", "Progreso", "San Antonio", "Santa Rosa", "Turpay", "Vilcabamba", "Virundo", "Curasco")),
        ),
    ),
    PeruRegionUi(
        name = "Arequipa",
        provinces = listOf(
            PeruProvinceUi("Arequipa", listOf("Arequipa", "Alto Selva Alegre", "Cayma", "Cerro Colorado", "Characato", "Chiguata", "Jacobo Hunter", "La Joya", "Mariano Melgar", "Miraflores", "Mollebaya", "Paucarpata", "Pocsi", "Polobaya", "Quequena", "Sabandia", "Sachaca", "San Juan de Siguas", "San Juan de Tarucani", "Santa Isabel de Siguas", "Santa Rita de Siguas", "Socabaya", "Tiabaya", "Uchumayo", "Vitor", "Yanahuara", "Yarabamba", "Yura", "Jose Luis Bustamante y Rivero")),
            PeruProvinceUi("Camana", listOf("Camana", "Jose Maria Quimper", "Mariano Nicolas Valcarcel", "Mariscal Caceres", "Nicolas de Pierola", "Ocona", "Quilca", "Samuel Pastor")),
            PeruProvinceUi("Caraveli", listOf("Caraveli", "Acari", "Atico", "Atiquipa", "Bella Union", "Cahuacho", "Chala", "Chaparra", "Huanuhuanu", "Jaqui", "Lomas", "Quicacha", "Yauca")),
            PeruProvinceUi("Castilla", listOf("Aplao", "Andagua", "Ayo", "Chachas", "Chilcaymarca", "Choco", "Huancarqui", "Machaguay", "Orcopampa", "Pampacolca", "Tipan", "Unon", "Uraca", "Viraco")),
            PeruProvinceUi("Caylloma", listOf("Chivay", "Achoma", "Cabanaconde", "Callalli", "Caylloma", "Coporaque", "Huambo", "Huanca", "Ichupampa", "Lari", "Lluta", "Maca", "Madrigal", "San Antonio de Chuca", "Sibayo", "Tapay", "Tisco", "Tuti", "Yanque", "Majes")),
            PeruProvinceUi("Condesuyos", listOf("Chuquibamba", "Andaray", "Cayarani", "Chichas", "Iray", "Rio Grande", "Salamanca", "Yanaquihua")),
            PeruProvinceUi("Islay", listOf("Mollendo", "Cocachacra", "Dean Valdivia", "Islay", "Mejia", "Punta de Bombon")),
            PeruProvinceUi("La Union", listOf("Cotahuasi", "Alca", "Charcana", "Huaynacotas", "Pampamarca", "Puyca", "Quechualla", "Sayla", "Tauria", "Tomepampa", "Toro")),
        ),
    ),
    PeruRegionUi(
        name = "Ayacucho",
        provinces = listOf(
            PeruProvinceUi("Huamanga", listOf("Ayacucho", "Acocro", "Acos Vinchos", "Carmen Alto", "Chiara", "Ocros", "Pacaycasa", "Quinua", "San Jose de Ticllas", "San Juan Bautista", "Santiago de Pischa", "Socos", "Tambillo", "Vinchos", "Jesus Nazareno", "Andres Avelino Caceres Dorregaray")),
            PeruProvinceUi("Cangallo", listOf("Cangallo", "Chuschi", "Los Morochucos", "Maria Parado de Bellido", "Paras", "Totos")),
            PeruProvinceUi("Huanca Sancos", listOf("Sancos", "Carapo", "Sacsamarca", "Santiago de Lucanamarca")),
            PeruProvinceUi("Huanta", listOf("Huanta", "Ayahuanco", "Huamanguilla", "Iguain", "Luricocha", "Santillana", "Sivia", "Llochegua", "Canayre", "Uchuraccay", "Pucacolpa", "Chaca")),
            PeruProvinceUi("La Mar", listOf("San Miguel", "Anco", "Ayna", "Chilcas", "Chungui", "Luis Carranza", "Santa Rosa", "Tambo", "Samugari", "Anchihuay", "Oronccoy")),
            PeruProvinceUi("Lucanas", listOf("Puquio", "Aucara", "Cabana", "Carmen Salcedo", "Chavina", "Chipao", "Huac-Huas", "Laramate", "Leoncio Prado", "Llauta", "Lucanas", "Ocana", "Otoca", "Saisa", "San Cristobal", "San Juan", "San Pedro", "San Pedro de Palco", "Sancos", "Santa Ana de Huaycahuacho", "Santa Lucia")),
            PeruProvinceUi("Parinacochas", listOf("Coracora", "Chumpi", "Coronel Castaneda", "Pacapausa", "Pullo", "Puyusca", "San Francisco de Ravacayco", "Upahuacho")),
            PeruProvinceUi("Paucar del Sara Sara", listOf("Pausa", "Colta", "Corculla", "Lampa", "Marcabamba", "Oyolo", "Pararca", "San Javier de Alpabamba", "San Jose de Ushua", "Sara Sara")),
            PeruProvinceUi("Sucre", listOf("Querobamba", "Belen", "Chalcos", "Chilcayoc", "Huacana", "Morcolla", "Paico", "San Pedro de Larcay", "San Salvador de Quije", "Santiago de Paucaray", "Soras")),
            PeruProvinceUi("Victor Fajardo", listOf("Huancapi", "Alcamenca", "Apongo", "Asquipata", "Canaria", "Cayara", "Colca", "Huamanquiquia", "Huancaraylla", "Huaya", "Sarhua", "Vilcanchos")),
            PeruProvinceUi("Vilcas Huaman", listOf("Vilcas Huaman", "Accomarca", "Carhuanca", "Concepcion", "Huambalpa", "Independencia", "Saurama", "Vischongo")),
        ),
    ),
    PeruRegionUi(
        name = "Cajamarca",
        provinces = listOf(
            PeruProvinceUi("Cajamarca", listOf("Cajamarca", "Asuncion", "Chetilla", "Cospan", "Encanada", "Jesus", "Llacanora", "Los Banos del Inca", "Magdalena", "Matara", "Namora", "San Juan")),
            PeruProvinceUi("Cajabamba", listOf("Cajabamba", "Cachachi", "Condebamba", "Sitacocha")),
            PeruProvinceUi("Celendin", listOf("Celendin", "Chumuch", "Cortegana", "Huasmin", "Jorge Chavez", "Jose Galvez", "Miguel Iglesias", "Oxamarca", "Sorochuco", "Sucre", "Utco", "La Libertad de Pallan")),
            PeruProvinceUi("Chota", listOf("Chota", "Anguia", "Chadin", "Chiguirip", "Chimban", "Choropampa", "Cochabamba", "Conchan", "Huambos", "Lajas", "Llama", "Miracosta", "Paccha", "Pion", "Querocoto", "San Juan de Licupis", "Tacabamba", "Tocmoche", "Chalamarca")),
            PeruProvinceUi("Contumaza", listOf("Contumaza", "Chilete", "Cupisnique", "Guzmango", "San Benito", "Santa Cruz de Toled", "Tantarica", "Yonan")),
            PeruProvinceUi("Cutervo", listOf("Cutervo", "Callayuc", "Choros", "Cujillo", "La Ramada", "Pimpingos", "Querocotillo", "San Andres de Cutervo", "San Juan de Cutervo", "San Luis de Lucma", "Santa Cruz", "Santo Domingo de La Capilla", "Santo Tomas", "Socota", "Toribio Casanova")),
            PeruProvinceUi("Hualgayoc", listOf("Bambamarca", "Chugur", "Hualgayoc")),
            PeruProvinceUi("Jaen", listOf("Jaen", "Bellavista", "Chontali", "Colasay", "Huabal", "Las Pirias", "Pomahuaca", "Pucara", "Sallique", "San Felipe", "San Jose del Alto", "Santa Rosa")),
            PeruProvinceUi("San Ignacio", listOf("San Ignacio", "Chirinos", "Huarango", "La Coipa", "Namballe", "San Jose de Lourdes", "Tabaconas")),
            PeruProvinceUi("San Marcos", listOf("Pedro Galvez", "Chancay", "Eduardo Villanueva", "Gregorio Pita", "Ichocan", "Jose Manuel Quiroz", "Jose Sabogal")),
            PeruProvinceUi("San Miguel", listOf("San Miguel", "Bolivar", "Calquis", "Catilluc", "El Prado", "La Florida", "Llapa", "Nanchoc", "Niepos", "San Gregorio", "San Silvestre de Cochan", "Tongod", "Union Agua Blanca")),
            PeruProvinceUi("San Pablo", listOf("San Pablo", "San Bernardino", "San Luis", "Tumbaden")),
            PeruProvinceUi("Santa Cruz", listOf("Santa Cruz", "Andabamba", "Catache", "Chancaybanos", "La Esperanza", "Ninabamba", "Pulan", "Saucepampa", "Sexi", "Uticyacu", "Yauyucan")),
        ),
    ),
    PeruRegionUi(
        name = "Callao",
        provinces = listOf(
            PeruProvinceUi("Callao", listOf("Callao", "Bellavista", "Carmen de La Legua", "La Perla", "La Punta", "Ventanilla", "Mi Peru")),
        ),
    ),
    PeruRegionUi(
        name = "Cusco",
        provinces = listOf(
            PeruProvinceUi("Cusco", listOf("Cusco", "Ccorca", "Poroy", "San Jeronimo", "San Sebastian", "Santiago", "Saylla", "Wanchaq")),
            PeruProvinceUi("Acomayo", listOf("Acomayo", "Acopia", "Acos", "Mosoc Llacta", "Pomacanchi", "Rondocan", "Sangarara")),
            PeruProvinceUi("Anta", listOf("Anta", "Ancahuasi", "Cachimayo", "Chinchaypujio", "Huarocondo", "Limatambo", "Mollepata", "Pucyura", "Zurite")),
            PeruProvinceUi("Calca", listOf("Calca", "Coya", "Lamay", "Lares", "Pisac", "San Salvador", "Taray", "Yanatile")),
            PeruProvinceUi("Canas", listOf("Yanaoca", "Checca", "Kunturkanki", "Langui", "Layo", "Pampamarca", "Quehue", "Tupac Amaru")),
            PeruProvinceUi("Canchis", listOf("Sicuani", "Checacupe", "Combapata", "Marangani", "Pitumarca", "San Pablo", "San Pedro", "Tinta")),
            PeruProvinceUi("Chumbivilcas", listOf("Santo Tomas", "Capacmarca", "Chamaca", "Colquemarca", "Livitaca", "Llusco", "Quinota", "Velille")),
            PeruProvinceUi("Espinar", listOf("Espinar", "Condoroma", "Coporaque", "Ocoruro", "Pallpata", "Pichigua", "Suyckutambo", "Alto Pichigua")),
            PeruProvinceUi("La Convencion", listOf("Santa Ana", "Echarate", "Huayopata", "Maranura", "Ocobamba", "Quellouno", "Kimbiri", "Santa Teresa", "Vilcabamba", "Pichari", "Inkawasi", "Villa Virgen", "Villa Kintiarina", "Megantoni")),
            PeruProvinceUi("Paruro", listOf("Paruro", "Accha", "Ccapi", "Colcha", "Huanoquite", "Omacha", "Paccaritambo", "Pillpinto", "Yaurisque")),
            PeruProvinceUi("Paucartambo", listOf("Paucartambo", "Caicay", "Challabamba", "Colquepata", "Huancarani", "Kosnipata")),
            PeruProvinceUi("Quispicanchi", listOf("Urcos", "Andahuaylillas", "Camanti", "Ccarhuayo", "Ccatca", "Cusipata", "Huaro", "Lucre", "Marcapata", "Ocongate", "Oropesa", "Quiquijana")),
            PeruProvinceUi("Urubamba", listOf("Urubamba", "Chinchero", "Huayllabamba", "Machupicchu", "Maras", "Ollantaytambo", "Yucay")),
        ),
    ),
    PeruRegionUi(
        name = "Huancavelica",
        provinces = listOf(
            PeruProvinceUi("Huancavelica", listOf("Huancavelica", "Acobambilla", "Acoria", "Conayca", "Cuenca", "Huachocolpa", "Huayllahuara", "Izcuchaca", "Laria", "Manta", "Mariscal Caceres", "Moya", "Nuevo Occoro", "Palca", "Pilchaca", "Vilca", "Yauli", "Ascension", "Huando")),
            PeruProvinceUi("Acobamba", listOf("Acobamba", "Andabamba", "Anta", "Caja", "Marcas", "Paucara", "Pomacocha", "Rosario")),
            PeruProvinceUi("Angaraes", listOf("Lircay", "Anchonga", "Callanmarca", "Ccochaccasa", "Chincho", "Congalla", "Huanca-Huanca", "Huayllay Grande", "Julcamarca", "San Antonio de Antaparco", "Santo Tomas de Pata", "Secclla")),
            PeruProvinceUi("Castrovirreyna", listOf("Castrovirreyna", "Arma", "Aurahua", "Capillas", "Chupamarca", "Cocas", "Huachos", "Huamatambo", "Mollepampa", "San Juan", "Santa Ana", "Tantara", "Ticrapo")),
            PeruProvinceUi("Churcampa", listOf("Churcampa", "Anco", "Chinchihuasi", "El Carmen", "La Merced", "Locroja", "Paucarbamba", "San Miguel de Mayocc", "San Pedro de Coris", "Pachamarca", "Cosme")),
            PeruProvinceUi("Huaytara", listOf("Huaytara", "Ayavi", "Cordova", "Huayacundo Arma", "Laramarca", "Ocoyo", "Pilpichaca", "Querco", "Quito-Arma", "San Antonio de Cusicancha", "San Francisco de Sangayaico", "San Isidro", "Santiago de Chocorvos", "Santiago de Quirahuara", "Santo Domingo de Capillas", "Tambo")),
            PeruProvinceUi("Tayacaja", listOf("Pampas", "Acostambo", "Acraquia", "Ahuaycha", "Colcabamba", "Daniel Hernandez", "Huachocolpa", "Huaribamba", "Nahuimpuquio", "Pazos", "Quishuar", "Salcabamba", "Salcahuasi", "San Marcos de Rocchac", "Surcubamba", "Tintay Puncu", "Quichuas", "Andaymarca", "Roble", "Pichos", "Santiago de Tucuma")),
        ),
    ),
    PeruRegionUi(
        name = "Huanuco",
        provinces = listOf(
            PeruProvinceUi("Huanuco", listOf("Huanuco", "Amarilis", "Chinchao", "Churubamba", "Margos", "Quisqui", "San Francisco de Cayran", "San Pedro de Chaulan", "Santa Maria del Valle", "Yarumayo", "Pillco Marca", "Yacus", "San Pablo de Pillao")),
            PeruProvinceUi("Ambo", listOf("Ambo", "Cayna", "Colpas", "Conchamarca", "Huacar", "San Francisco", "San Rafael", "Tomay Kichwa")),
            PeruProvinceUi("Dos de Mayo", listOf("La Union", "Chuquis", "Marias", "Pachas", "Quivilla", "Ripan", "Shunqui", "Sillapata", "Yanas")),
            PeruProvinceUi("Huacaybamba", listOf("Huacaybamba", "Canchabamba", "Cochabamba", "Pinra")),
            PeruProvinceUi("Huamalies", listOf("Llata", "Arancay", "Chavin de Pariarca", "Jacas Grande", "Jircan", "Miraflores", "Monzon", "Punchao", "Punos", "Singa", "Tantamayo")),
            PeruProvinceUi("Leoncio Prado", listOf("Rupa-Rupa", "Daniel Alomias Robles", "Hermilio Valdizan", "Jose Crespo y Castillo", "Luyando", "Mariano Damaso Beraun", "Pucayacu", "Castillo Grande", "Pueblo Nuevo", "Santo Domingo de Anda")),
            PeruProvinceUi("Maranon", listOf("Huacrachuco", "Cholon", "San Buenaventura", "La Morada", "Santa Rosa de Alto Yanajanca")),
            PeruProvinceUi("Pachitea", listOf("Panao", "Chaglla", "Molino", "Umari")),
            PeruProvinceUi("Puerto Inca", listOf("Puerto Inca", "Codo del Pozuzo", "Honoria", "Tournavista", "Yuyapichis")),
            PeruProvinceUi("Lauricocha", listOf("Jesus", "Banos", "Jivia", "Queropalca", "Rondos", "San Francisco de Asis", "San Miguel de Cauri")),
            PeruProvinceUi("Yarowilca", listOf("Chavinillo", "Cahuac", "Chacabamba", "Aparicio Pomares", "Jacas Chico", "Obas", "Pampamarca", "Choras")),
        ),
    ),
    PeruRegionUi(
        name = "Ica",
        provinces = listOf(
            PeruProvinceUi("Ica", listOf("Ica", "La Tinguina", "Los Aquijes", "Ocucaje", "Pachacutec", "Parcona", "Pueblo Nuevo", "Salas", "San Jose de los Molinos", "San Juan Bautista", "Santiago", "Subtanjalla", "Tate", "Yauca del Rosario")),
            PeruProvinceUi("Chincha", listOf("Chincha Alta", "Alto Laran", "Chavin", "Chincha Baja", "El Carmen", "Grocio Prado", "Pueblo Nuevo", "San Juan de Yanac", "San Pedro de Huacarpana", "Sunampe", "Tambo de Mora")),
            PeruProvinceUi("Nazca", listOf("Nazca", "Changuillo", "El Ingenio", "Marcona", "Vista Alegre")),
            PeruProvinceUi("Palpa", listOf("Palpa", "Llipata", "Rio Grande", "Santa Cruz", "Tibillo")),
            PeruProvinceUi("Pisco", listOf("Pisco", "Huancano", "Humay", "Independencia", "Paracas", "San Andres", "San Clemente", "Tupac Amaru Inca")),
        ),
    ),
    PeruRegionUi(
        name = "Junin",
        provinces = listOf(
            PeruProvinceUi("Huancayo", listOf("Huancayo", "Carhuacallanga", "Chacapampa", "Chicche", "Chilca", "Chongos Alto", "Chupuro", "Colca", "Cullhuas", "El Tambo", "Huacrapuquio", "Hualhuas", "Huancan", "Huasicancha", "Huayucachi", "Ingenio", "Pariahuanca", "Pilcomayo", "Pucara", "Quichuay", "Quilcas", "San Agustin", "San Jeronimo de Tunan", "Sano", "Sapallanga", "Sicaya", "Santo Domingo de Acobamba", "Viques")),
            PeruProvinceUi("Concepcion", listOf("Concepcion", "Aco", "Andamarca", "Chambara", "Cochas", "Comas", "Heroinas Toledo", "Manzanares", "Mariscal Castilla", "Matahuasi", "Mito", "Nueve de Julio", "Orcotuna", "San Jose de Quero", "Santa Rosa de Ocopa")),
            PeruProvinceUi("Chanchamayo", listOf("Chanchamayo", "Perene", "Pichanaqui", "San Luis de Shuaro", "San Ramon", "Vitoc")),
            PeruProvinceUi("Jauja", listOf("Jauja", "Acolla", "Apata", "Ataura", "Canchayllo", "Curicaca", "El Mantaro", "Huamali", "Huaripampa", "Huertas", "Janjaillo", "Julcan", "Leonor Ordonez", "Llocllapampa", "Marco", "Masma", "Masma Chicche", "Molinos", "Monobamba", "Muqui", "Muquiyauyo", "Paca", "Paccha", "Pancan", "Parco", "Pomacancha", "Ricran", "San Lorenzo", "San Pedro de Chunan", "Sausa", "Sincos", "Tunan Marca", "Yauli", "Yauyos")),
            PeruProvinceUi("Junin", listOf("Junin", "Carhuamayo", "Ondores", "Ulcumayo")),
            PeruProvinceUi("Satipo", listOf("Satipo", "Coviriali", "Llaylla", "Mazamari", "Pampa Hermosa", "Pangoa", "Rio Negro", "Rio Tambo", "Vizcatan del Ene")),
            PeruProvinceUi("Tarma", listOf("Tarma", "Acobamba", "Huaricolca", "Huasahuasi", "La Union", "Palca", "Palcamayo", "San Pedro de Cajas", "Tapo")),
            PeruProvinceUi("Yauli", listOf("La Oroya", "Chacapalpa", "Huay-Huay", "Marcapomacocha", "Morococha", "Paccha", "Santa Barbara de Carhuacayan", "Santa Rosa de Sacco", "Suitucancha", "Yauli")),
            PeruProvinceUi("Chupaca", listOf("Chupaca", "Ahuac", "Chongos Bajo", "Huachac", "Huamancaca Chico", "San Juan de Yscos", "San Juan de Jarpa", "Tres de Diciembre", "Yanacancha")),
        ),
    ),
    PeruRegionUi(
        name = "La Libertad",
        provinces = listOf(
            PeruProvinceUi("Trujillo", listOf("Trujillo", "El Porvenir", "Florencia de Mora", "Huanchaco", "La Esperanza", "Laredo", "Moche", "Poroto", "Salaverry", "Simbal", "Victor Larco Herrera")),
            PeruProvinceUi("Ascope", listOf("Ascope", "Chicama", "Chocope", "Magdalena de Cao", "Paijan", "Razuri", "Santiago de Cao", "Casa Grande")),
            PeruProvinceUi("Bolivar", listOf("Bolivar", "Bambamarca", "Condormarca", "Longotea", "Uchumarca", "Ucuncha")),
            PeruProvinceUi("Chepen", listOf("Chepen", "Pacanga", "Pueblo Nuevo")),
            PeruProvinceUi("Julcan", listOf("Julcan", "Calamarca", "Carabamba", "Huaso")),
            PeruProvinceUi("Otuzco", listOf("Otuzco", "Agallpampa", "Charat", "Huaranchal", "La Cuesta", "Mache", "Paranday", "Salpo", "Sinsicap", "Usquil")),
            PeruProvinceUi("Pacasmayo", listOf("San Pedro de Lloc", "Guadalupe", "Jequetepeque", "Pacasmayo", "San Jose")),
            PeruProvinceUi("Pataz", listOf("Tayabamba", "Buldibuyo", "Chillia", "Huancaspata", "Huaylillas", "Huayo", "Ongon", "Parcoy", "Pataz", "Pias", "Santiago de Challas", "Taurija", "Urpay")),
            PeruProvinceUi("Sanchez Carrion", listOf("Huamachuco", "Chugay", "Cochorco", "Curgos", "Marcabal", "Sanagoran", "Sarin", "Sartimbamba")),
            PeruProvinceUi("Santiago de Chuco", listOf("Santiago de Chuco", "Angasmarca", "Cachicadan", "Mollebamba", "Mollepata", "Quiruvilca", "Santa Cruz de Chuca", "Sitabamba")),
            PeruProvinceUi("Gran Chimu", listOf("Cascas", "Lucma", "Compin", "Sayapullo")),
            PeruProvinceUi("Viru", listOf("Viru", "Chao", "Guadalupito")),
        ),
    ),
    PeruRegionUi(
        name = "Lambayeque",
        provinces = listOf(
            PeruProvinceUi("Chiclayo", listOf("Chiclayo", "Chongoyape", "Eten", "Eten Puerto", "Jose Leonardo Ortiz", "La Victoria", "Lagunas", "Monsefu", "Nueva Arica", "Oyotun", "Picsi", "Pimentel", "Reque", "Santa Rosa", "Sana", "Cayalti", "Patapo", "Pomalca", "Pucala", "Tuman")),
            PeruProvinceUi("Ferrenafe", listOf("Ferrenafe", "Canaris", "Incahuasi", "Manuel Antonio Mesones Muro", "Pitipo", "Pueblo Nuevo")),
            PeruProvinceUi("Lambayeque", listOf("Lambayeque", "Chochope", "Illimo", "Jayanca", "Mochumi", "Morrope", "Motupe", "Olmos", "Pacora", "Salas", "San Jose", "Tucume")),
        ),
    ),
    PeruRegionUi(
        name = "Lima",
        provinces = listOf(
            PeruProvinceUi("Lima", listOf("Lima", "Ancon", "Ate", "Barranco", "Brena", "Carabayllo", "Chaclacayo", "Chorrillos", "Cieneguilla", "Comas", "El Agustino", "Independencia", "Jesus Maria", "La Molina", "La Victoria", "Lince", "Los Olivos", "Lurigancho", "Lurin", "Magdalena del Mar", "Pueblo Libre", "Miraflores", "Pachacamac", "Pucusana", "Puente Piedra", "Punta Hermosa", "Punta Negra", "Rimac", "San Bartolo", "San Borja", "San Isidro", "San Juan de Lurigancho", "San Juan de Miraflores", "San Luis", "San Martin de Porres", "San Miguel", "Santa Anita", "Santa Maria del Mar", "Santa Rosa", "Santiago de Surco", "Surquillo", "Villa El Salvador", "Villa Maria del Triunfo")),
            PeruProvinceUi("Barranca", listOf("Barranca", "Paramonga", "Pativilca", "Supe", "Supe Puerto")),
            PeruProvinceUi("Cajatambo", listOf("Cajatambo", "Copa", "Gorgor", "Huancapon", "Manas")),
            PeruProvinceUi("Canta", listOf("Canta", "Arahuay", "Huamantanga", "Huaros", "Lachaqui", "San Buenaventura", "Santa Rosa de Quives")),
            PeruProvinceUi("Canete", listOf("San Vicente de Canete", "Asia", "Calango", "Cerro Azul", "Chilca", "Coayllo", "Imperial", "Lunahuana", "Mala", "Nuevo Imperial", "Pacaran", "Quilmana", "San Antonio", "San Luis", "Santa Cruz de Flores", "Zuniga")),
            PeruProvinceUi("Huaral", listOf("Huaral", "Atavillos Alto", "Atavillos Bajo", "Aucallama", "Chancay", "Ihuari", "Lampian", "Pacaraos", "San Miguel de Acos", "Santa Cruz de Andamarca", "Sumbilca", "Veintisiete de Noviembre")),
            PeruProvinceUi("Huarochiri", listOf("Matucana", "Antioquia", "Callahuanca", "Carampoma", "Chicla", "Cuenca", "Huachupampa", "Huanza", "Huarochiri", "Lahuaytambo", "Langa", "Laraos", "Mariatana", "Ricardo Palma", "San Andres de Tupicocha", "San Antonio", "San Bartolome", "San Damian", "San Juan de Iris", "San Juan de Tantaranche", "San Lorenzo de Quinti", "San Mateo", "San Mateo de Otao", "San Pedro de Casta", "San Pedro de Huancayre", "Sangallaya", "Santa Cruz de Cocachacra", "Santa Eulalia", "Santiago de Anchucaya", "Santiago de Tuna", "Santo Domingo de los Olleros", "Surco")),
            PeruProvinceUi("Huaura", listOf("Huacho", "Ambar", "Caleta de Carquin", "Checras", "Hualmay", "Huaura", "Leoncio Prado", "Paccho", "Santa Leonor", "Santa Maria", "Sayan", "Vegueta")),
            PeruProvinceUi("Oyon", listOf("Oyon", "Andajes", "Caujul", "Cochamarca", "Navan", "Pachangara")),
            PeruProvinceUi("Yauyos", listOf("Yauyos", "Alis", "Ayauca", "Ayaviri", "Azangaro", "Cacra", "Carania", "Catahuasi", "Chocos", "Cochas", "Colonia", "Hongos", "Huampara", "Huancaya", "Huangascar", "Huantan", "Huanec", "Laraos", "Lincha", "Madean", "Miraflores", "Omas", "Putinza", "Quinches", "Quinocay", "San Joaquin", "San Pedro de Pilas", "Tanta", "Tauripampa", "Tomas", "Tupe", "Vinac", "Vitis")),
        ),
    ),
    PeruRegionUi(
        name = "Loreto",
        provinces = listOf(
            PeruProvinceUi("Maynas", listOf("Iquitos", "Alto Nanay", "Fernando Lores", "Indiana", "Las Amazonas", "Mazan", "Napo", "Punchana", "Torres Causana", "Belen", "San Juan Bautista", "Putumayo", "Rosa Panduro", "Teniente Manuel Clavero", "Yaguas")),
            PeruProvinceUi("Alto Amazonas", listOf("Yurimaguas", "Balsapuerto", "Jeberos", "Lagunas", "Santa Cruz", "Teniente Cesar Lopez Rojas")),
            PeruProvinceUi("Loreto", listOf("Nauta", "Parinari", "Tigre", "Trompeteros", "Urarinas")),
            PeruProvinceUi("Mariscal Ramon Castilla", listOf("Ramon Castilla", "Pebas", "Yavari", "San Pablo")),
            PeruProvinceUi("Requena", listOf("Requena", "Alto Tapiche", "Capelo", "Emilio San Martin", "Maquia", "Puinahua", "Saquena", "Soplin", "Tapiche", "Jenaro Herrera", "Yaquerana")),
            PeruProvinceUi("Ucayali", listOf("Contamana", "Inahuaya", "Padre Marquez", "Pampa Hermosa", "Sarayacu", "Vargas Guerra")),
            PeruProvinceUi("Datem del Maranon", listOf("Barranca", "Cahuapanas", "Manseriche", "Morona", "Pastaza", "Andoas")),
        ),
    ),
    PeruRegionUi(
        name = "Madre de Dios",
        provinces = listOf(
            PeruProvinceUi("Tambopata", listOf("Tambopata", "Inambari", "Las Piedras", "Laberinto")),
            PeruProvinceUi("Manu", listOf("Manu", "Fitzcarrald", "Madre de Dios", "Huepetuhe")),
            PeruProvinceUi("Tahuamanu", listOf("Inapari", "Iberia", "Tahuamanu")),
        ),
    ),
    PeruRegionUi(
        name = "Moquegua",
        provinces = listOf(
            PeruProvinceUi("Mariscal Nieto", listOf("Moquegua", "Carumas", "Cuchumbaya", "Samegua", "San Cristobal", "Torata")),
            PeruProvinceUi("General Sanchez Cerr", listOf("Omate", "Chojata", "Coalaque", "Ichuna", "La Capilla", "Lloque", "Matalaque", "Puquina", "Quinistaquillas", "Ubinas", "Yunga")),
            PeruProvinceUi("Ilo", listOf("Ilo", "El Algarrobal", "Pacocha")),
        ),
    ),
    PeruRegionUi(
        name = "Pasco",
        provinces = listOf(
            PeruProvinceUi("Pasco", listOf("Chaupimarca", "Huachon", "Huariaca", "Huayllay", "Ninacaca", "Pallanchacra", "Paucartambo", "San Francisco de Asis de Yarusyacan", "Simon Bolivar", "Ticlacayan", "Tinyahuarco", "Vicco", "Yanacancha")),
            PeruProvinceUi("Daniel Alcides Carri", listOf("Yanahuanca", "Chacayan", "Goyllarisquizga", "Paucar", "San Pedro de Pillao", "Santa Ana de Tusi", "Tapuc", "Vilcabamba")),
            PeruProvinceUi("Oxapampa", listOf("Oxapampa", "Chontabamba", "Huancabamba", "Palcazu", "Pozuzo", "Puerto Bermudez", "Villa Rica", "Constitucion")),
        ),
    ),
    PeruRegionUi(
        name = "Piura",
        provinces = listOf(
            PeruProvinceUi("Piura", listOf("Piura", "Castilla", "Catacaos", "Cura Mori", "El Tallan", "La Arena", "La Union", "Las Lomas", "Tambo Grande", "26 de Octubre")),
            PeruProvinceUi("Ayabaca", listOf("Ayabaca", "Frias", "Jilili", "Lagunas", "Montero", "Pacaipampa", "Paimas", "Sapillica", "Sicchez", "Suyo")),
            PeruProvinceUi("Huancabamba", listOf("Huancabamba", "Canchaque", "El Carmen de La Frontera", "Huarmaca", "Lalaquiz", "San Miguel de El Faique", "Sondor", "Sondorillo")),
            PeruProvinceUi("Morropon", listOf("Chulucanas", "Buenos Aires", "Chalaco", "La Matanza", "Morropon", "Salitral", "San Juan de Bigote", "Santa Catalina de Mossa", "Santo Domingo", "Yamango")),
            PeruProvinceUi("Paita", listOf("Paita", "Amotape", "Arenal", "Colan", "La Huaca", "Tamarindo", "Vichayal")),
            PeruProvinceUi("Sullana", listOf("Sullana", "Bellavista", "Ignacio Escudero", "Lancones", "Marcavelica", "Miguel Checa", "Querecotillo", "Salitral")),
            PeruProvinceUi("Talara", listOf("Parinas", "El Alto", "La Brea", "Lobitos", "Los Organos", "Mancora")),
            PeruProvinceUi("Sechura", listOf("Sechura", "Bellavista de La Union", "Bernal", "Cristo Nos Valga", "Vice", "Rinconada Llicuar")),
        ),
    ),
    PeruRegionUi(
        name = "Puno",
        provinces = listOf(
            PeruProvinceUi("Puno", listOf("Puno", "Acora", "Amantani", "Atuncolla", "Capachica", "Chucuito", "Coata", "Huata", "Manazo", "Paucarcolla", "Pichacani", "Plateria", "San Antonio", "Tiquillaca", "Vilque")),
            PeruProvinceUi("Azangaro", listOf("Azangaro", "Achaya", "Arapa", "Asillo", "Caminaca", "Chupa", "Jose Domingo Choquehuanca", "Munani", "Potoni", "Saman", "San Anton", "San Jose", "San Juan de Salinas", "Santiago de Pupuja", "Tirapata")),
            PeruProvinceUi("Carabaya", listOf("Macusani", "Ajoyani", "Ayapata", "Coasa", "Corani", "Crucero", "Ituata", "Ollachea", "San Gaban", "Usicayos")),
            PeruProvinceUi("Chucuito", listOf("Juli", "Desaguadero", "Huacullani", "Kelluyo", "Pisacoma", "Pomata", "Zepita")),
            PeruProvinceUi("El Collao", listOf("Ilave", "Capazo", "Pilcuyo", "Santa Rosa", "Conduriri")),
            PeruProvinceUi("Huancane", listOf("Huancane", "Cojata", "Huatasani", "Inchupalla", "Pusi", "Rosaspata", "Taraco", "Vilque Chico")),
            PeruProvinceUi("Lampa", listOf("Lampa", "Cabanilla", "Calapuja", "Nicasio", "Ocuviri", "Palca", "Paratia", "Pucara", "Santa Lucia", "Vilavila")),
            PeruProvinceUi("Melgar", listOf("Ayaviri", "Antauta", "Cupi", "Llalli", "Macari", "Nunoa", "Orurillo", "Santa Rosa", "Umachiri")),
            PeruProvinceUi("Moho", listOf("Moho", "Conima", "Huayrapata", "Tilali")),
            PeruProvinceUi("San Antonio de Putin", listOf("Putina", "Ananea", "Pedro Vilca Apaza", "Quilcapuncu", "Sina")),
            PeruProvinceUi("San Roman", listOf("Juliaca", "Cabana", "Cabanillas", "Caracoto", "San Miguel")),
            PeruProvinceUi("Sandia", listOf("Sandia", "Cuyocuyo", "Limbani", "Patambuco", "Phara", "Quiaca", "San Juan del Oro", "Yanahuaya", "Alto Inambari", "San Pedro de Putina Punco")),
            PeruProvinceUi("Yunguyo", listOf("Yunguyo", "Anapia", "Copani", "Cuturapi", "Ollaraya", "Tinicachi", "Unicachi")),
        ),
    ),
    PeruRegionUi(
        name = "San Martin",
        provinces = listOf(
            PeruProvinceUi("Moyobamba", listOf("Moyobamba", "Calzada", "Habana", "Jepelacio", "Soritor", "Yantalo")),
            PeruProvinceUi("Bellavista", listOf("Bellavista", "Alto Biavo", "Bajo Biavo", "Huallaga", "San Pablo", "San Rafael")),
            PeruProvinceUi("El Dorado", listOf("San Jose de Sisa", "Agua Blanca", "San Martin", "Santa Rosa", "Shatoja")),
            PeruProvinceUi("Huallaga", listOf("Saposoa", "Alto Saposoa", "El Eslabon", "Piscoyacu", "Sacanche", "Tingo de Saposoa")),
            PeruProvinceUi("Lamas", listOf("Lamas", "Alonso de Alvarado", "Barranquita", "Caynarachi", "Cunumbuqui", "Pinto Recodo", "Rumisapa", "San Roque de Cumbaza", "Shanao", "Tabalosos", "Zapatero")),
            PeruProvinceUi("Mariscal Caceres", listOf("Juanjui", "Campanilla", "Huicungo", "Pachiza", "Pajarillo")),
            PeruProvinceUi("Picota", listOf("Picota", "Buenos Aires", "Caspisapa", "Pilluana", "Pucacaca", "San Cristobal", "San Hilarion", "Shamboyacu", "Tingo de Ponasa", "Tres Unidos")),
            PeruProvinceUi("Rioja", listOf("Rioja", "Awajun", "Elias Soplin Vargas", "Nueva Cajamarca", "Pardo Miguel", "Posic", "San Fernando", "Yorongos", "Yuracyacu")),
            PeruProvinceUi("San Martin", listOf("Tarapoto", "Alberto Leveau", "Cacatachi", "Chazuta", "Chipurana", "El Porvenir", "Huimbayoc", "Juan Guerra", "La Banda de Shilcayo", "Morales", "Papaplaya", "San Antonio", "Sauce", "Shapaja")),
            PeruProvinceUi("Tocache", listOf("Tocache", "Nuevo Progreso", "Polvora", "Shunte", "Uchiza")),
        ),
    ),
    PeruRegionUi(
        name = "Tacna",
        provinces = listOf(
            PeruProvinceUi("Tacna", listOf("Tacna", "Alto de La Alianza", "Calana", "Ciudad Nueva", "Inclan", "Pachia", "Palca", "Pocollay", "Sama", "Coronel Gregorio Albarracin Lanchipa", "La Yarada-Los Palos")),
            PeruProvinceUi("Candarave", listOf("Candarave", "Cairani", "Camilaca", "Curibaya", "Huanuara", "Quilahuani")),
            PeruProvinceUi("Jorge Basadre", listOf("Locumba", "Ilabaya", "Ite")),
            PeruProvinceUi("Tarata", listOf("Tarata", "Heroes Albarracin", "Estique", "Estique-Pampa", "Sitajara", "Susapaya", "Tarucachi", "Ticaco")),
        ),
    ),
    PeruRegionUi(
        name = "Tumbes",
        provinces = listOf(
            PeruProvinceUi("Tumbes", listOf("Tumbes", "Corrales", "La Cruz", "Pampas de Hospital", "San Jacinto", "San Juan de La Virgen")),
            PeruProvinceUi("Contralmirante Villa", listOf("Zorritos", "Casitas", "Canoas de Punta Sal")),
            PeruProvinceUi("Zarumilla", listOf("Zarumilla", "Aguas Verdes", "Matapalo", "Papayal")),
        ),
    ),
    PeruRegionUi(
        name = "Ucayali",
        provinces = listOf(
            PeruProvinceUi("Coronel Portillo", listOf("Calleria", "Campoverde", "Iparia", "Masisea", "Yarinacocha", "Nueva Requena", "Manantay")),
            PeruProvinceUi("Atalaya", listOf("Raymondi", "Sepahua", "Tahuania", "Yurua")),
            PeruProvinceUi("Padre Abad", listOf("Padre Abad", "Irazola", "Curimana", "Neshuya", "Alexander von Humboldt")),
            PeruProvinceUi("Purus", listOf("Purus")),
        ),
    ),
)
